include("shared.lua")
include("gui/hud/cl_hud.lua")
include("gui/inventory/cl_inventory.lua")
include("player/stamina/cl_stamina.lua")
include("player/spawn/cl_spawn.lua")
include("player/health/cl_health.lua")
include("player/needs/cl_needs.lua")